### ISSUE TITLE
Simple updates not merging due to conflict with snakeyaml

### ISSUE THREAD

**Issue by BrianAtAustin** [xvik/yaml-updater#38]
Using yaml-updater 1.4.1 (via Maven) I wrote a simple unit test with the below files attached (files should be renamed to .yml ... I made them text files to allow them to be uploaded). The unit test then simply did the following

    @Test
    public void testBugSubmission() {

        // ===== Given =====

        File badFile = getFile("Rivk-bug-missing-foo.yml");
        assertTrue(badFile.exists());
        File templateFile = getFile("Rivk-bug-ok.yml");

        // ===== When ======

        UpdateReport report = YamlUpdater.create(badFile, templateFile).update();
       // etc
      }

I got an IllegalStateException with the following trace (which asked for a bug report, so here it is!):

Thanks,
Brian @ Austin

java.lang.IllegalStateException: Failed to update: original configuration remains

	at ru.vyarus.yaml.updater.YamlUpdater.execute(YamlUpdater.java:164)
	at ru.vyarus.yaml.updater.UpdateConfig$Configurator.update(UpdateConfig.java:320)
	at com.<company>.common.logging.RivkYamlUpdaterTest.testBugSubmission(RivkYamlUpdaterTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalStateException: Model validation fail: comments parser tree does not match snakeyaml's parse tree for update config
	at ru.vyarus.yaml.updater.YamlUpdater.prepareNewConfig(YamlUpdater.java:194)
	at ru.vyarus.yaml.updater.YamlUpdater.execute(YamlUpdater.java:158)
	... 67 more
Caused by: java.lang.IllegalStateException: Comments parser validation problem on line 3: 0 child nodes found but should be at least 2 (this is a parser bug, please report it!)
      Comments parser subtree:    Structure parser subtree:
         3| - --                     4| toplevel:
                                     6|   foo: bar
                                     7|   baz:
                                     9|     a.b.c: z
                                    10|     a.b.c.d: y
                                    11|     a.b.c.e: x

	at ru.vyarus.yaml.updater.update.CommentsParserValidator.validateSubtrees(CommentsParserValidator.java:50)
	at ru.vyarus.yaml.updater.update.CommentsParserValidator.validateSubtrees(CommentsParserValidator.java:84)
	at ru.vyarus.yaml.updater.update.CommentsParserValidator.validate(CommentsParserValidator.java:40)
	at ru.vyarus.yaml.updater.YamlUpdater.prepareNewConfig(YamlUpdater.java:192)
	... 68 more

[Rivk-bug-ok.txt](https://github.com/xvik/yaml-updater/files/8125345/Rivk-bug-ok.txt)
[RIvk-bug-missing-foo.txt](https://github.com/xvik/yaml-updater/files/8125352/RIvk-bug-missing-foo.txt)

**Comment by BrianAtAustin** [comment]
Sorry, for some reason I thought your username was Rvik! My apologies, xvik!

**Comment by xvik** [comment]
Thank you very much for the report! 
The problem is in the document start marker: `---`.
`---` is generally used for separation of multiple yaml documents in one file, but
comments parser supports only subset of yaml features, and does not support multiple yaml objects in one file (supposed to be used for simple case - configs).

You can just remove `---` and it will work in the current updater version.

But it is still a bug that parser accepted `---` line, so i'll look it (but later). Also, I'll look to support sych syntax, at least in cases like yours (when it could be easilly ignored).

> Sorry, for some reason I thought your username was Rvik! My apologies, xvik!

no problem)

**Comment by BrianAtAustin** [comment]
Xvik,

Removing the document start marker ‘—‘ did work. Thank you for the note.

Brian


I have some Yaml like 

Brian Bankler — Principal Engineer
***@***.***
Big Lever, Inc <https://www.biglever.com/>
(210)-414-1629
